In [4]:
! pip install -Uqq fastai 

In [ ]:
!pip list | grep torch

In [1]:
import torch
x = torch.tensor(([1,2,3],[4,5,6]),dtype=torch.float32)
x.shape


torch.Size([2, 3])

In [63]:
# tensor 添加一行
y = torch.tensor([7,8,3])
y = y.unsqueeze(0)
y,torch.cat((x,y),dim=0)


(tensor([[7, 8, 3]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 3.]]))

In [64]:
# tensor 添加一列
y = torch.tensor([7,8])
y = y.unsqueeze(1)
z = torch.cat((x,y), dim=1)
y,z

(tensor([[7],
         [8]]),
 tensor([[1., 2., 3., 7.],
         [4., 5., 6., 8.]]))

In [65]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [75]:
64//3


21

In [5]:
from fastai.text.all import *

In [6]:
@Transform
def f(x:int): return x+1
f(2),f(2.0)

(3, 2.0)

In [7]:
class NormalizeMean(Transform):
    def setups(self, items): self.mean = sum(items)/len(items)
    def encodes(self, x): return x-self.mean
    def decodes(self, x): return x+self.mean

tfm = NormalizeMean()
tfm.setups([1,2,3,4,5])
start = 2
tfm.decodes(start)

In [12]:
tfm = NormalizeMean()
tfm.setups([1,2,3,4,5])
start = 2
tfm.decodes(start)


5.0

In [13]:
Animals= ["cat", "dog", "tiger"]
Animals[0]

'cat'

In [17]:
x = tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
x

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [18]:
x[:, 1]

tensor([1.2000, 3.1000, 5.2000])

In [1]:
import ipywidgets as widgets
slider = widgets.IntSlider(value=5, min=0, max=10, step=1)
slider

In [2]:
slider = widgets.IntSlider(value=5, min=0, max=10, step=1)
slider

IntSlider(value=5, max=10)

In [ ]:
from ipywidgets import interact

@interact
def greet(name="World", count=5):
    for _ in range(count):
        print(f"Hello, {name}!")

greet()