In [4]:
! pip install -Uqq fastai 

In [ ]:
!pip list | grep torch

In [1]:
import torch
x = torch.tensor(([1,2,3],[4,5,6]),dtype=torch.float32)
x.shape


torch.Size([2, 3])

In [63]:
# tensor 添加一行
y = torch.tensor([7,8,3])
y = y.unsqueeze(0)
y,torch.cat((x,y),dim=0)


(tensor([[7, 8, 3]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 3.]]))

In [64]:
# tensor 添加一列
y = torch.tensor([7,8])
y = y.unsqueeze(1)
z = torch.cat((x,y), dim=1)
y,z

(tensor([[7],
         [8]]),
 tensor([[1., 2., 3., 7.],
         [4., 5., 6., 8.]]))

In [65]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [75]:
64//3


21

In [5]:
from fastai.text.all import *

In [6]:
@Transform
def f(x:int): return x+1
f(2),f(2.0)

(3, 2.0)

In [7]:
class NormalizeMean(Transform):
    def setups(self, items): self.mean = sum(items)/len(items)
    def encodes(self, x): return x-self.mean
    def decodes(self, x): return x+self.mean

tfm = NormalizeMean()
tfm.setups([1,2,3,4,5])
start = 2
tfm.decodes(start)

In [12]:
tfm = NormalizeMean()
tfm.setups([1,2,3,4,5])
start = 2
tfm.decodes(start)


5.0

In [13]:
Animals= ["cat", "dog", "tiger"]
Animals[0]

'cat'

In [ ]:
dls = DataLoaders.from_dsets(seqs[:cut], seqs[cut:], bs=64, shuffle=False)