In [ ]:
! pip install torch 

In [ ]:
!pip list | grep torch

In [38]:
import torch
x = torch.tensor(([1,2,3],[4,5,6]),dtype=torch.float32)
x.shape


torch.Size([2, 3])

In [63]:
# tensor 添加一行
y = torch.tensor([7,8,3])
y = y.unsqueeze(0)
y,torch.cat((x,y),dim=0)


(tensor([[7, 8, 3]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 3.]]))

In [64]:
# tensor 添加一列
y = torch.tensor([7,8])
y = y.unsqueeze(1)
z = torch.cat((x,y), dim=1)
y,z

(tensor([[7],
         [8]]),
 tensor([[1., 2., 3., 7.],
         [4., 5., 6., 8.]]))

In [65]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [68]:
?? torch.mm

Docstring:
mm(input, mat2, *, out=None) -> Tensor

Performs a matrix multiplication of the matrices :attr:`input` and :attr:`mat2`.

If :attr:`input` is a :math:`(n \times m)` tensor, :attr:`mat2` is a
:math:`(m \times p)` tensor, :attr:`out` will be a :math:`(n \times p)` tensor.

.. note:: This function does not :ref:`broadcast <broadcasting-semantics>`.
          For broadcasting matrix products, see :func:`torch.matmul`.

Supports strided and sparse 2-D tensors as inputs, autograd with
respect to strided inputs.

This operation has support for arguments with :ref:`sparse layouts<sparse-docs>`.
If :attr:`out` is provided it's layout will be used. Otherwise, the result
layout will be deduced from that of :attr:`input`.


.. warning::
    Sparse support is a beta feature and some layout(s)/dtype/device combinations may not be supported,
    or may not have autograd support. If you notice missing functionality please
    open a feature request.

This operator supports :ref:`TensorFloat